[package]
name = "media_info"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg-next = "6.0.0"
kamadak-exif = "0.5.5"
chrono = "0.4.24"
id3 = "1.7.0"
file_metadata = { path = "../file_metadata" }